// This file is auto-generated by @hey-api/openapi-ts

export const AIProviderSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2
    ],
    title: 'AIProvider',
    'x-enum-varnames': [
        'UNKNOWN',
        'ANTHROPIC',
        'OPENAI'
    ]
} as const;

export const AnswerReadSchema = {
    properties: {
        testResultId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Testresultid'
        },
        questionId: {
            type: 'string',
            title: 'Questionid'
        },
        userAnswer: {
            type: 'string',
            title: 'Useranswer'
        },
        status: {
            $ref: '#/components/schemas/AnswerStatus'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        rubricResult: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/RubricResultItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rubricresult'
        }
    },
    type: 'object',
    required: [
        'questionId',
        'userAnswer',
        'status',
        'id'
    ],
    title: 'AnswerRead'
} as const;

export const AnswerStatusSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2,
        3,
        4,
        5
    ],
    title: 'AnswerStatus',
    'x-enum-varnames': [
        'UNKNOWN',
        'CORRECT',
        'WRONG',
        'PARTIAL',
        'PENDING',
        'FAILED'
    ]
} as const;

export const Body_usersLoginSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_usersLogin'
} as const;

export const ChallengeRequestSchema = {
    properties: {
        criteria: {
            items: {
                $ref: '#/components/schemas/CriterionChallengeInput'
            },
            type: 'array',
            minItems: 1,
            title: 'Criteria'
        }
    },
    type: 'object',
    required: [
        'criteria'
    ],
    title: 'ChallengeRequest'
} as const;

export const ChallengeResultItemSchema = {
    properties: {
        argument: {
            type: 'string',
            title: 'Argument'
        },
        met: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Met'
        },
        reason: {
            type: 'string',
            title: 'Reason',
            default: ''
        }
    },
    type: 'object',
    required: [
        'argument'
    ],
    title: 'ChallengeResultItem'
} as const;

export const CriterionChallengeInputSchema = {
    properties: {
        criterionIndex: {
            type: 'integer',
            minimum: 0,
            title: 'Criterionindex'
        },
        argument: {
            type: 'string',
            maxLength: 500,
            minLength: 1,
            title: 'Argument'
        }
    },
    type: 'object',
    required: [
        'criterionIndex',
        'argument'
    ],
    title: 'CriterionChallengeInput'
} as const;

export const GeneratedQuestionPreview_InputSchema = {
    properties: {
        questionType: {
            $ref: '#/components/schemas/QuestionType'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SimpleContent'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContent'
                },
                {
                    $ref: '#/components/schemas/LongTextContent'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    required: [
        'questionType',
        'prompt',
        'content'
    ],
    title: 'GeneratedQuestionPreview'
} as const;

export const GeneratedQuestionPreview_OutputSchema = {
    properties: {
        questionType: {
            $ref: '#/components/schemas/QuestionType'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SimpleContent'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContent'
                },
                {
                    $ref: '#/components/schemas/LongTextContent'
                }
            ],
            title: 'Content'
        }
    },
    type: 'object',
    required: [
        'questionType',
        'prompt',
        'content'
    ],
    title: 'GeneratedQuestionPreview'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const LongTextContentSchema = {
    properties: {
        lengthLimit: {
            $ref: '#/components/schemas/LongTextLength'
        },
        rubric: {
            items: {
                $ref: '#/components/schemas/RubricItem'
            },
            type: 'array',
            minItems: 1,
            title: 'Rubric'
        }
    },
    type: 'object',
    required: [
        'lengthLimit',
        'rubric'
    ],
    title: 'LongTextContent'
} as const;

export const LongTextContentStrippedSchema = {
    properties: {
        lengthLimit: {
            $ref: '#/components/schemas/LongTextLength'
        },
        rubric: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/RubricItem'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rubric'
        }
    },
    type: 'object',
    required: [
        'lengthLimit'
    ],
    title: 'LongTextContentStripped'
} as const;

export const LongTextLengthSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2,
        3
    ],
    title: 'LongTextLength',
    'x-enum-varnames': [
        'UNKNOWN',
        'SHORT',
        'MEDIUM',
        'LONG'
    ]
} as const;

export const MultipleChoiceContentSchema = {
    properties: {
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 6,
            minItems: 2,
            title: 'Options'
        },
        correctIndices: {
            items: {
                type: 'integer'
            },
            type: 'array',
            minItems: 1,
            title: 'Correctindices'
        }
    },
    type: 'object',
    required: [
        'options',
        'correctIndices'
    ],
    title: 'MultipleChoiceContent'
} as const;

export const MultipleChoiceContentStrippedSchema = {
    properties: {
        options: {
            items: {
                type: 'string'
            },
            type: 'array',
            maxItems: 6,
            minItems: 2,
            title: 'Options'
        },
        correctIndices: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correctindices'
        }
    },
    type: 'object',
    required: [
        'options'
    ],
    title: 'MultipleChoiceContentStripped'
} as const;

export const NoteChunkEditSchema = {
    properties: {
        fullText: {
            type: 'string',
            minLength: 1,
            title: 'Fulltext'
        },
        selectedText: {
            type: 'string',
            minLength: 1,
            title: 'Selectedtext'
        },
        instructions: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Instructions'
        }
    },
    type: 'object',
    required: [
        'fullText',
        'selectedText',
        'instructions'
    ],
    title: 'NoteChunkEdit'
} as const;

export const NoteChunkEditResponseSchema = {
    properties: {
        editedText: {
            type: 'string',
            title: 'Editedtext'
        }
    },
    type: 'object',
    required: [
        'editedText'
    ],
    title: 'NoteChunkEditResponse'
} as const;

export const NoteCreateSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 200,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content: {
            type: 'string',
            title: 'Content',
            default: ''
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'NoteCreate'
} as const;

export const NoteGenerateSchema = {
    properties: {
        topic: {
            type: 'string',
            maxLength: 200,
            title: 'Topic'
        },
        guidance: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance'
        },
        length: {
            anyOf: [
                {
                    $ref: '#/components/schemas/NoteLength'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'topic'
    ],
    title: 'NoteGenerate'
} as const;

export const NoteLengthSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2,
        3
    ],
    title: 'NoteLength',
    'x-enum-varnames': [
        'UNKNOWN',
        'SHORT',
        'MEDIUM',
        'LONG'
    ]
} as const;

export const NoteReadSchema = {
    properties: {
        title: {
            type: 'string',
            maxLength: 200,
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content: {
            type: 'string',
            title: 'Content',
            default: ''
        },
        tags: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Tags',
            default: []
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        userId: {
            type: 'string',
            title: 'Userid'
        },
        source: {
            $ref: '#/components/schemas/NoteSource'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        updatedAt: {
            type: 'string',
            format: 'date-time',
            title: 'Updatedat'
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'userId',
        'source',
        'createdAt',
        'updatedAt'
    ],
    title: 'NoteRead'
} as const;

export const NoteRefineSchema = {
    properties: {
        instructions: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Instructions'
        }
    },
    type: 'object',
    required: [
        'instructions'
    ],
    title: 'NoteRefine'
} as const;

export const NoteSourceSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2
    ],
    title: 'NoteSource',
    'x-enum-varnames': [
        'UNKNOWN',
        'USER_CREATED',
        'AI_GENERATED'
    ]
} as const;

export const NoteUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 200
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        content: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        tags: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Tags'
        }
    },
    type: 'object',
    title: 'NoteUpdate'
} as const;

export const QuestionAnswerSchema = {
    properties: {
        questionId: {
            type: 'string',
            title: 'Questionid'
        },
        userAnswer: {
            type: 'string',
            title: 'Useranswer'
        }
    },
    type: 'object',
    required: [
        'questionId',
        'userAnswer'
    ],
    title: 'QuestionAnswer',
    description: 'A single answer within a test submission.'
} as const;

export const QuestionCheckRequestSchema = {
    properties: {
        userAnswer: {
            type: 'string',
            title: 'Useranswer'
        }
    },
    type: 'object',
    required: [
        'userAnswer'
    ],
    title: 'QuestionCheckRequest',
    description: 'Payload for checking a single question answer.'
} as const;

export const QuestionCheckResponseSchema = {
    properties: {
        status: {
            $ref: '#/components/schemas/AnswerStatus'
        },
        correctAnswers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correctanswers'
        },
        correctIndices: {
            anyOf: [
                {
                    items: {
                        type: 'integer'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Correctindices'
        },
        srsState: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SRSStateResponse'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'QuestionCheckResponse',
    description: 'Response for a single question check.'
} as const;

export const QuestionCreateSchema = {
    properties: {
        questionType: {
            $ref: '#/components/schemas/QuestionType'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SimpleContent'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContent'
                },
                {
                    $ref: '#/components/schemas/LongTextContent'
                }
            ],
            title: 'Content'
        },
        hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hint'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        testId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Testid'
        },
        groupId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groupid'
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        }
    },
    type: 'object',
    required: [
        'questionType',
        'prompt',
        'content'
    ],
    title: 'QuestionCreate'
} as const;

export const QuestionEditRequestSchema = {
    properties: {
        selectedIndices: {
            items: {
                type: 'integer'
            },
            type: 'array',
            minItems: 1,
            title: 'Selectedindices'
        },
        allQuestions: {
            items: {
                $ref: '#/components/schemas/GeneratedQuestionPreview-Input'
            },
            type: 'array',
            title: 'Allquestions'
        },
        instructions: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Instructions'
        },
        noteContent: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Notecontent'
        }
    },
    type: 'object',
    required: [
        'selectedIndices',
        'allQuestions',
        'instructions'
    ],
    title: 'QuestionEditRequest'
} as const;

export const QuestionGroupTypeSchema = {
    type: 'integer',
    enum: [
        0,
        1
    ],
    title: 'QuestionGroupType',
    'x-enum-varnames': [
        'UNKNOWN',
        'VOCABULARY'
    ]
} as const;

export const QuestionReadSchema = {
    properties: {
        questionType: {
            $ref: '#/components/schemas/QuestionType'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SimpleContent'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContent'
                },
                {
                    $ref: '#/components/schemas/LongTextContent'
                }
            ],
            title: 'Content'
        },
        hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hint'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        testId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Testid'
        },
        groupId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groupid'
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        originId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Originid'
        }
    },
    type: 'object',
    required: [
        'questionType',
        'prompt',
        'content',
        'id'
    ],
    title: 'QuestionRead'
} as const;

export const QuestionReadStrippedSchema = {
    properties: {
        questionType: {
            $ref: '#/components/schemas/QuestionType'
        },
        prompt: {
            type: 'string',
            title: 'Prompt'
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/LongTextContentStripped'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContentStripped'
                },
                {
                    $ref: '#/components/schemas/SimpleContentStripped'
                }
            ],
            title: 'Content'
        },
        hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hint'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        testId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Testid'
        },
        groupId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Groupid'
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        id: {
            type: 'string',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'questionType',
        'prompt',
        'content',
        'id'
    ],
    title: 'QuestionReadStripped',
    description: 'QuestionRead with answer fields optional — used when answers are stripped before serving.'
} as const;

export const QuestionTypeSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2,
        3
    ],
    title: 'QuestionType',
    'x-enum-varnames': [
        'UNKNOWN',
        'SIMPLE',
        'MULTIPLE_CHOICE',
        'LONG_TEXT'
    ]
} as const;

export const QuestionUpdateSchema = {
    properties: {
        questionType: {
            anyOf: [
                {
                    $ref: '#/components/schemas/QuestionType'
                },
                {
                    type: 'null'
                }
            ]
        },
        prompt: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Prompt'
        },
        content: {
            anyOf: [
                {
                    $ref: '#/components/schemas/SimpleContent'
                },
                {
                    $ref: '#/components/schemas/MultipleChoiceContent'
                },
                {
                    $ref: '#/components/schemas/LongTextContent'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Content'
        },
        hint: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hint'
        },
        explanation: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Explanation'
        },
        points: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Points'
        }
    },
    type: 'object',
    title: 'QuestionUpdate'
} as const;

export const ReviewResponseSchema = {
    properties: {
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionReadStripped'
            },
            type: 'array',
            title: 'Questions'
        },
        hasQuestions: {
            type: 'boolean',
            title: 'Hasquestions'
        }
    },
    type: 'object',
    required: [
        'questions',
        'hasQuestions'
    ],
    title: 'ReviewResponse'
} as const;

export const RubricItemSchema = {
    properties: {
        point: {
            type: 'string',
            title: 'Point',
            description: 'The concept or fact the user must mention'
        },
        weight: {
            type: 'number',
            maximum: 1,
            minimum: 0,
            title: 'Weight',
            description: 'Score contribution (0.0 to 1.0)'
        },
        category: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Category',
            description: 'Optional grouping label (e.g. \'Key Events\')'
        }
    },
    type: 'object',
    required: [
        'point',
        'weight'
    ],
    title: 'RubricItem'
} as const;

export const RubricResultItemSchema = {
    properties: {
        point: {
            type: 'string',
            title: 'Point'
        },
        met: {
            type: 'boolean',
            title: 'Met'
        },
        weight: {
            type: 'number',
            title: 'Weight'
        },
        reason: {
            type: 'string',
            title: 'Reason',
            default: ''
        },
        challengeResult: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ChallengeResultItem'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'point',
        'met',
        'weight'
    ],
    title: 'RubricResultItem'
} as const;

export const SRSStateResponseSchema = {
    properties: {
        easeFactor: {
            type: 'number',
            title: 'Easefactor'
        },
        interval: {
            type: 'integer',
            title: 'Interval'
        },
        repetitions: {
            type: 'integer',
            title: 'Repetitions'
        },
        nextReview: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Nextreview'
        }
    },
    type: 'object',
    required: [
        'easeFactor',
        'interval',
        'repetitions'
    ],
    title: 'SRSStateResponse'
} as const;

export const SimpleContentSchema = {
    properties: {
        answers: {
            items: {
                type: 'string'
            },
            type: 'array',
            minItems: 1,
            title: 'Answers'
        }
    },
    type: 'object',
    required: [
        'answers'
    ],
    title: 'SimpleContent'
} as const;

export const SimpleContentStrippedSchema = {
    properties: {
        answers: {
            anyOf: [
                {
                    items: {
                        type: 'string'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Answers'
        }
    },
    type: 'object',
    title: 'SimpleContentStripped'
} as const;

export const TestCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionCreate'
            },
            type: 'array',
            title: 'Questions',
            default: []
        },
        questionGroups: {
            items: {
                $ref: '#/components/schemas/TestQuestionGroupCreate'
            },
            type: 'array',
            title: 'Questiongroups',
            default: []
        },
        sourceNoteId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sourcenoteid'
        }
    },
    type: 'object',
    required: [
        'title'
    ],
    title: 'TestCreate'
} as const;

export const TestGenerationRequestSchema = {
    properties: {
        noteId: {
            type: 'string',
            title: 'Noteid'
        },
        questionCount: {
            type: 'integer',
            maximum: 30,
            minimum: 5,
            title: 'Questioncount'
        },
        questionTypes: {
            items: {
                $ref: '#/components/schemas/QuestionType'
            },
            type: 'array',
            title: 'Questiontypes'
        },
        difficulty: {
            type: 'string',
            enum: [
                'easy',
                'medium',
                'hard'
            ],
            title: 'Difficulty'
        },
        guidance: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 2000
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance'
        }
    },
    type: 'object',
    required: [
        'noteId',
        'questionCount',
        'questionTypes',
        'difficulty'
    ],
    title: 'TestGenerationRequest'
} as const;

export const TestGenerationResponseSchema = {
    properties: {
        questions: {
            items: {
                $ref: '#/components/schemas/GeneratedQuestionPreview-Output'
            },
            type: 'array',
            title: 'Questions'
        },
        sourceNoteId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sourcenoteid'
        },
        sourceNoteTitle: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sourcenotetitle'
        },
        warning: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Warning'
        }
    },
    type: 'object',
    required: [
        'questions'
    ],
    title: 'TestGenerationResponse'
} as const;

export const TestQuestionGroupCreateSchema = {
    properties: {
        type: {
            $ref: '#/components/schemas/QuestionGroupType',
            default: 0
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionCreate'
            },
            type: 'array',
            title: 'Questions',
            default: []
        }
    },
    type: 'object',
    title: 'TestQuestionGroupCreate'
} as const;

export const TestQuestionGroupReadSchema = {
    properties: {
        type: {
            $ref: '#/components/schemas/QuestionGroupType',
            default: 0
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        testId: {
            type: 'string',
            title: 'Testid'
        },
        originId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Originid'
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionRead'
            },
            type: 'array',
            title: 'Questions',
            default: []
        }
    },
    type: 'object',
    required: [
        'id',
        'testId'
    ],
    title: 'TestQuestionGroupRead'
} as const;

export const TestQuestionGroupReadStrippedSchema = {
    properties: {
        type: {
            $ref: '#/components/schemas/QuestionGroupType',
            default: 0
        },
        order: {
            type: 'integer',
            title: 'Order',
            default: 0
        },
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        points: {
            type: 'number',
            title: 'Points',
            default: 1
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        testId: {
            type: 'string',
            title: 'Testid'
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionReadStripped'
            },
            type: 'array',
            title: 'Questions',
            default: []
        }
    },
    type: 'object',
    required: [
        'id',
        'testId'
    ],
    title: 'TestQuestionGroupReadStripped'
} as const;

export const TestReadSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        userId: {
            type: 'string',
            title: 'Userid'
        },
        status: {
            $ref: '#/components/schemas/TestStatus'
        },
        sourceNoteId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sourcenoteid'
        },
        version: {
            type: 'integer',
            title: 'Version',
            default: 1
        },
        parentId: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Parentid'
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionRead'
            },
            type: 'array',
            title: 'Questions',
            default: []
        },
        questionGroups: {
            items: {
                $ref: '#/components/schemas/TestQuestionGroupRead'
            },
            type: 'array',
            title: 'Questiongroups',
            default: []
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'userId',
        'status'
    ],
    title: 'TestRead'
} as const;

export const TestReadStrippedSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        userId: {
            type: 'string',
            title: 'Userid'
        },
        status: {
            $ref: '#/components/schemas/TestStatus'
        },
        questions: {
            items: {
                $ref: '#/components/schemas/QuestionReadStripped'
            },
            type: 'array',
            title: 'Questions',
            default: []
        },
        questionGroups: {
            items: {
                $ref: '#/components/schemas/TestQuestionGroupReadStripped'
            },
            type: 'array',
            title: 'Questiongroups',
            default: []
        }
    },
    type: 'object',
    required: [
        'title',
        'id',
        'userId',
        'status'
    ],
    title: 'TestReadStripped'
} as const;

export const TestRefinementRequestSchema = {
    properties: {
        noteId: {
            type: 'string',
            title: 'Noteid'
        },
        currentQuestions: {
            items: {
                $ref: '#/components/schemas/GeneratedQuestionPreview-Input'
            },
            type: 'array',
            title: 'Currentquestions'
        },
        instructions: {
            type: 'string',
            maxLength: 2000,
            minLength: 1,
            title: 'Instructions'
        }
    },
    type: 'object',
    required: [
        'noteId',
        'currentQuestions',
        'instructions'
    ],
    title: 'TestRefinementRequest'
} as const;

export const TestResultListItemSchema = {
    properties: {
        id: {
            type: 'string',
            title: 'Id'
        },
        testId: {
            type: 'string',
            title: 'Testid'
        },
        testTitle: {
            type: 'string',
            title: 'Testtitle'
        },
        score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Score',
            default: 0
        },
        totalQuestions: {
            type: 'integer',
            title: 'Totalquestions'
        },
        correctAnswers: {
            type: 'integer',
            title: 'Correctanswers'
        },
        pendingAnswers: {
            type: 'integer',
            title: 'Pendinganswers',
            default: 0
        },
        earnedPoints: {
            type: 'number',
            title: 'Earnedpoints',
            default: 0
        },
        totalPoints: {
            type: 'number',
            title: 'Totalpoints',
            default: 0
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        }
    },
    type: 'object',
    required: [
        'id',
        'testId',
        'testTitle',
        'totalQuestions',
        'correctAnswers',
        'createdAt'
    ],
    title: 'TestResultListItem',
    description: 'Lightweight schema for the history list — no answers array.'
} as const;

export const TestResultReadSchema = {
    properties: {
        testId: {
            type: 'string',
            title: 'Testid'
        },
        userId: {
            type: 'string',
            title: 'Userid'
        },
        score: {
            type: 'number',
            maximum: 100,
            minimum: 0,
            title: 'Score',
            default: 0
        },
        totalQuestions: {
            type: 'integer',
            title: 'Totalquestions'
        },
        correctAnswers: {
            type: 'integer',
            title: 'Correctanswers'
        },
        pendingAnswers: {
            type: 'integer',
            title: 'Pendinganswers',
            default: 0
        },
        earnedPoints: {
            type: 'number',
            title: 'Earnedpoints',
            default: 0
        },
        totalPoints: {
            type: 'number',
            title: 'Totalpoints',
            default: 0
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        createdAt: {
            type: 'string',
            format: 'date-time',
            title: 'Createdat'
        },
        answers: {
            items: {
                $ref: '#/components/schemas/AnswerRead'
            },
            type: 'array',
            title: 'Answers',
            default: []
        }
    },
    type: 'object',
    required: [
        'testId',
        'userId',
        'totalQuestions',
        'correctAnswers',
        'id',
        'createdAt'
    ],
    title: 'TestResultRead'
} as const;

export const TestStatusSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2
    ],
    title: 'TestStatus',
    'x-enum-varnames': [
        'UNKNOWN',
        'ACTIVE',
        'DELETED'
    ]
} as const;

export const TestSubmissionSchema = {
    properties: {
        answers: {
            items: {
                $ref: '#/components/schemas/QuestionAnswer'
            },
            type: 'array',
            title: 'Answers'
        }
    },
    type: 'object',
    required: [
        'answers'
    ],
    title: 'TestSubmission',
    description: 'Payload for submitting a full test for correction.'
} as const;

export const TestUpdateSchema = {
    properties: {
        title: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        questions: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/QuestionCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Questions'
        },
        questionGroups: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/TestQuestionGroupCreate'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Questiongroups'
        }
    },
    type: 'object',
    title: 'TestUpdate'
} as const;

export const TokenUsageDailySummarySchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        provider: {
            $ref: '#/components/schemas/AIProvider'
        },
        inputTokens: {
            type: 'integer',
            title: 'Inputtokens'
        },
        outputTokens: {
            type: 'integer',
            title: 'Outputtokens'
        },
        estimatedCost: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Estimatedcost'
        }
    },
    type: 'object',
    required: [
        'date',
        'provider',
        'inputTokens',
        'outputTokens',
        'estimatedCost'
    ],
    title: 'TokenUsageDailySummary'
} as const;

export const TokenUsageSummaryResponseSchema = {
    properties: {
        daily: {
            items: {
                $ref: '#/components/schemas/TokenUsageDailySummary'
            },
            type: 'array',
            title: 'Daily'
        },
        totalInputTokens: {
            type: 'integer',
            title: 'Totalinputtokens'
        },
        totalOutputTokens: {
            type: 'integer',
            title: 'Totaloutputtokens'
        },
        totalEstimatedCost: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Totalestimatedcost'
        }
    },
    type: 'object',
    required: [
        'daily',
        'totalInputTokens',
        'totalOutputTokens',
        'totalEstimatedCost'
    ],
    title: 'TokenUsageSummaryResponse'
} as const;

export const UserCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'username',
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserReadSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        id: {
            type: 'string',
            title: 'Id'
        },
        status: {
            $ref: '#/components/schemas/UserStatus'
        },
        role: {
            $ref: '#/components/schemas/UserRole'
        },
        displayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Displayname'
        },
        locale: {
            type: 'string',
            title: 'Locale',
            default: 'en'
        },
        theme: {
            type: 'string',
            title: 'Theme',
            default: 'system'
        },
        aiProvider: {
            anyOf: [
                {
                    $ref: '#/components/schemas/AIProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        hasAnthropicKey: {
            type: 'boolean',
            title: 'Hasanthropickey',
            default: false
        },
        hasOpenaiKey: {
            type: 'boolean',
            title: 'Hasopenaikey',
            default: false
        },
        dailyReviewLimit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dailyreviewlimit'
        },
        initialEaseFactor: {
            type: 'number',
            title: 'Initialeasefactor',
            default: 2.5
        }
    },
    type: 'object',
    required: [
        'username',
        'email',
        'id',
        'status',
        'role'
    ],
    title: 'UserRead'
} as const;

export const UserRoleSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2
    ],
    title: 'UserRole',
    'x-enum-varnames': [
        'UNKNOWN',
        'ADMIN',
        'USER'
    ]
} as const;

export const UserStatusSchema = {
    type: 'integer',
    enum: [
        0,
        1,
        2,
        3
    ],
    title: 'UserStatus',
    'x-enum-varnames': [
        'UNKNOWN',
        'ACTIVE',
        'DELETED',
        'BLOCKED'
    ]
} as const;

export const UserUpdateSchema = {
    properties: {
        displayName: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Displayname'
        },
        locale: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Locale'
        },
        theme: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Theme'
        },
        aiProvider: {
            anyOf: [
                {
                    $ref: '#/components/schemas/AIProvider'
                },
                {
                    type: 'null'
                }
            ]
        },
        anthropicApiKey: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Anthropicapikey'
        },
        openaiApiKey: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Openaiapikey'
        },
        dailyReviewLimit: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Dailyreviewlimit'
        },
        initialEaseFactor: {
            anyOf: [
                {
                    type: 'number'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Initialeasefactor'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        },
        input: {
            title: 'Input'
        },
        ctx: {
            type: 'object',
            title: 'Context'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;
