// This file is auto-generated by @hey-api/openapi-ts

import type { FoldersCreateResponse, FoldersListResponse, FoldersTreeResponse, FoldersUpdateResponse, NotesCreateResponse, NotesGenerateResponse, NotesGetResponse, NotesMoveResponse, NotesSetFavoriteResponse, NotesUpdateResponse, QuestionsCheckResponse, ResultsGetResponse, ResultsListResponse, TestsCreateResponse, TestsGetResponse, TestsListResponse, TestsSubmitResponse, TestsUpdateResponse, TrashFolderTreeResponse, TrashListResponse, TrashTreeResponse } from './types.gen';

const testReadSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const paginatedResponseTestReadSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => testReadSchemaResponseTransformer(item));
    return data;
};

export const testsListResponseTransformer = async (data: any): Promise<TestsListResponse> => {
    data = paginatedResponseTestReadSchemaResponseTransformer(data);
    return data;
};

export const testsCreateResponseTransformer = async (data: any): Promise<TestsCreateResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

export const testsGetResponseTransformer = async (data: any): Promise<TestsGetResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

export const testsUpdateResponseTransformer = async (data: any): Promise<TestsUpdateResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

const testResultReadSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const testsSubmitResponseTransformer = async (data: any): Promise<TestsSubmitResponse> => {
    data = testResultReadSchemaResponseTransformer(data);
    return data;
};

const testResultListItemSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const paginatedResponseTestResultListItemSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => testResultListItemSchemaResponseTransformer(item));
    return data;
};

export const resultsListResponseTransformer = async (data: any): Promise<ResultsListResponse> => {
    data = paginatedResponseTestResultListItemSchemaResponseTransformer(data);
    return data;
};

export const resultsGetResponseTransformer = async (data: any): Promise<ResultsGetResponse> => {
    data = testResultReadSchemaResponseTransformer(data);
    return data;
};

const srsStateResponseSchemaResponseTransformer = (data: any) => {
    if (data.nextReview) {
        data.nextReview = new Date(data.nextReview);
    }
    return data;
};

const questionCheckResponseSchemaResponseTransformer = (data: any) => {
    if (data.srsState) {
        data.srsState = srsStateResponseSchemaResponseTransformer(data.srsState);
    }
    return data;
};

export const questionsCheckResponseTransformer = async (data: any): Promise<QuestionsCheckResponse> => {
    data = questionCheckResponseSchemaResponseTransformer(data);
    return data;
};

const folderReadSchemaResponseTransformer = (data: any) => {
    if (data.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const foldersListResponseTransformer = async (data: any): Promise<FoldersListResponse> => {
    data = data.map((item: any) => folderReadSchemaResponseTransformer(item));
    return data;
};

export const foldersCreateResponseTransformer = async (data: any): Promise<FoldersCreateResponse> => {
    data = folderReadSchemaResponseTransformer(data);
    return data;
};

const fileTreeFolderSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const fileTreeNoteSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    if (data.favoritedAt) {
        data.favoritedAt = new Date(data.favoritedAt);
    }
    return data;
};

const fileTreeSchemaResponseTransformer = (data: any) => {
    data.folders = data.folders.map((item: any) => fileTreeFolderSchemaResponseTransformer(item));
    data.notes = data.notes.map((item: any) => fileTreeNoteSchemaResponseTransformer(item));
    return data;
};

export const foldersTreeResponseTransformer = async (data: any): Promise<FoldersTreeResponse> => {
    data = fileTreeSchemaResponseTransformer(data);
    return data;
};

export const foldersUpdateResponseTransformer = async (data: any): Promise<FoldersUpdateResponse> => {
    data = folderReadSchemaResponseTransformer(data);
    return data;
};

const noteReadSchemaResponseTransformer = (data: any) => {
    if (data.favoritedAt) {
        data.favoritedAt = new Date(data.favoritedAt);
    }
    if (data.deletedAt) {
        data.deletedAt = new Date(data.deletedAt);
    }
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

export const notesGenerateResponseTransformer = async (data: any): Promise<NotesGenerateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesGetResponseTransformer = async (data: any): Promise<NotesGetResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesUpdateResponseTransformer = async (data: any): Promise<NotesUpdateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesCreateResponseTransformer = async (data: any): Promise<NotesCreateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesMoveResponseTransformer = async (data: any): Promise<NotesMoveResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesSetFavoriteResponseTransformer = async (data: any): Promise<NotesSetFavoriteResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

const trashItemReadSchemaResponseTransformer = (data: any) => {
    data.deletedAt = new Date(data.deletedAt);
    return data;
};

export const trashListResponseTransformer = async (data: any): Promise<TrashListResponse> => {
    data = data.map((item: any) => trashItemReadSchemaResponseTransformer(item));
    return data;
};

const trashTreeFolderSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    data.deletedAt = new Date(data.deletedAt);
    return data;
};

const trashTreeNoteSchemaResponseTransformer = (data: any) => {
    data.updatedAt = new Date(data.updatedAt);
    if (data.favoritedAt) {
        data.favoritedAt = new Date(data.favoritedAt);
    }
    data.deletedAt = new Date(data.deletedAt);
    return data;
};

const trashTreeSchemaResponseTransformer = (data: any) => {
    data.folders = data.folders.map((item: any) => trashTreeFolderSchemaResponseTransformer(item));
    data.notes = data.notes.map((item: any) => trashTreeNoteSchemaResponseTransformer(item));
    return data;
};

export const trashTreeResponseTransformer = async (data: any): Promise<TrashTreeResponse> => {
    data = trashTreeSchemaResponseTransformer(data);
    return data;
};

export const trashFolderTreeResponseTransformer = async (data: any): Promise<TrashFolderTreeResponse> => {
    data = fileTreeSchemaResponseTransformer(data);
    return data;
};
