// This file is auto-generated by @hey-api/openapi-ts

import type { NotesCreateResponse, NotesGenerateResponse, NotesGetResponse, NotesListResponse, NotesRefineResponse, NotesUpdateResponse, QuestionsCheckResponse, ResultsGetResponse, ResultsListResponse, TestsCreateResponse, TestsGetResponse, TestsListResponse, TestsSubmitResponse, TestsUpdateResponse, TokenUsageGetUsageResponse } from './types.gen';

const testReadSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const paginatedResponseTestReadSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => testReadSchemaResponseTransformer(item));
    return data;
};

export const testsListResponseTransformer = async (data: any): Promise<TestsListResponse> => {
    data = paginatedResponseTestReadSchemaResponseTransformer(data);
    return data;
};

export const testsCreateResponseTransformer = async (data: any): Promise<TestsCreateResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

export const testsGetResponseTransformer = async (data: any): Promise<TestsGetResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

export const testsUpdateResponseTransformer = async (data: any): Promise<TestsUpdateResponse> => {
    data = testReadSchemaResponseTransformer(data);
    return data;
};

const testResultReadSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

export const testsSubmitResponseTransformer = async (data: any): Promise<TestsSubmitResponse> => {
    data = testResultReadSchemaResponseTransformer(data);
    return data;
};

const testResultListItemSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    return data;
};

const paginatedResponseTestResultListItemSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => testResultListItemSchemaResponseTransformer(item));
    return data;
};

export const resultsListResponseTransformer = async (data: any): Promise<ResultsListResponse> => {
    data = paginatedResponseTestResultListItemSchemaResponseTransformer(data);
    return data;
};

export const resultsGetResponseTransformer = async (data: any): Promise<ResultsGetResponse> => {
    data = testResultReadSchemaResponseTransformer(data);
    return data;
};

const srsStateResponseSchemaResponseTransformer = (data: any) => {
    if (data.nextReview) {
        data.nextReview = new Date(data.nextReview);
    }
    return data;
};

const questionCheckResponseSchemaResponseTransformer = (data: any) => {
    if (data.srsState) {
        data.srsState = srsStateResponseSchemaResponseTransformer(data.srsState);
    }
    return data;
};

export const questionsCheckResponseTransformer = async (data: any): Promise<QuestionsCheckResponse> => {
    data = questionCheckResponseSchemaResponseTransformer(data);
    return data;
};

const noteReadSchemaResponseTransformer = (data: any) => {
    data.createdAt = new Date(data.createdAt);
    data.updatedAt = new Date(data.updatedAt);
    return data;
};

const paginatedResponseNoteReadSchemaResponseTransformer = (data: any) => {
    data.items = data.items.map((item: any) => noteReadSchemaResponseTransformer(item));
    return data;
};

export const notesListResponseTransformer = async (data: any): Promise<NotesListResponse> => {
    data = paginatedResponseNoteReadSchemaResponseTransformer(data);
    return data;
};

export const notesCreateResponseTransformer = async (data: any): Promise<NotesCreateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesGenerateResponseTransformer = async (data: any): Promise<NotesGenerateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesGetResponseTransformer = async (data: any): Promise<NotesGetResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesUpdateResponseTransformer = async (data: any): Promise<NotesUpdateResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

export const notesRefineResponseTransformer = async (data: any): Promise<NotesRefineResponse> => {
    data = noteReadSchemaResponseTransformer(data);
    return data;
};

const tokenUsageDailySummarySchemaResponseTransformer = (data: any) => {
    data.date = new Date(data.date);
    return data;
};

const tokenUsageSummaryResponseSchemaResponseTransformer = (data: any) => {
    data.daily = data.daily.map((item: any) => tokenUsageDailySummarySchemaResponseTransformer(item));
    return data;
};

export const tokenUsageGetUsageResponseTransformer = async (data: any): Promise<TokenUsageGetUsageResponse> => {
    data = tokenUsageSummaryResponseSchemaResponseTransformer(data);
    return data;
};
