// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AIProvider
 */
export enum AiProvider {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * ANTHROPIC
     */
    ANTHROPIC = 1,
    /**
     * OPENAI
     */
    OPENAI = 2
}

/**
 * AnswerRead
 */
export type AnswerRead = {
    /**
     * Testresultid
     */
    testResultId?: string | null;
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Useranswer
     */
    userAnswer: string;
    status: AnswerStatus;
    /**
     * Id
     */
    id: string;
    /**
     * Rubricresult
     */
    rubricResult?: Array<RubricResultItem> | null;
};

/**
 * AnswerStatus
 */
export enum AnswerStatus {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * CORRECT
     */
    CORRECT = 1,
    /**
     * WRONG
     */
    WRONG = 2,
    /**
     * PARTIAL
     */
    PARTIAL = 3,
    /**
     * PENDING
     */
    PENDING = 4,
    /**
     * FAILED
     */
    FAILED = 5
}

/**
 * AssignQuestionRequest
 */
export type AssignQuestionRequest = {
    /**
     * Testid
     */
    testId: string;
};

/**
 * Body_usersLogin
 */
export type BodyUsersLogin = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * BulkAssignQuestionsRequest
 */
export type BulkAssignQuestionsRequest = {
    /**
     * Questionids
     */
    questionIds: Array<string>;
    /**
     * Testid
     */
    testId: string;
};

/**
 * BulkAssignQuestionsResponse
 */
export type BulkAssignQuestionsResponse = {
    /**
     * Assigned
     */
    assigned: number;
};

/**
 * BulkDeleteQuestionsRequest
 */
export type BulkDeleteQuestionsRequest = {
    /**
     * Questionids
     */
    questionIds: Array<string>;
};

/**
 * BulkDeleteQuestionsResponse
 */
export type BulkDeleteQuestionsResponse = {
    /**
     * Deleted
     */
    deleted: number;
};

/**
 * ChallengeRequest
 */
export type ChallengeRequest = {
    /**
     * Criteria
     */
    criteria: Array<CriterionChallengeInput>;
};

/**
 * ChallengeResultItem
 */
export type ChallengeResultItem = {
    /**
     * Argument
     */
    argument: string;
    /**
     * Met
     */
    met?: boolean | null;
    /**
     * Reason
     */
    reason?: string;
};

/**
 * CriterionChallengeInput
 */
export type CriterionChallengeInput = {
    /**
     * Criterionindex
     */
    criterionIndex: number;
    /**
     * Argument
     */
    argument: string;
};

/**
 * GeneratedQuestionPreview
 */
export type GeneratedQuestionPreviewInput = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Points
     */
    points?: number;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
};

/**
 * GeneratedQuestionPreview
 */
export type GeneratedQuestionPreviewOutput = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Points
     */
    points?: number;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * LongTextContent
 */
export type LongTextContent = {
    lengthLimit: LongTextLength;
    /**
     * Rubric
     */
    rubric: Array<RubricItem>;
};

/**
 * LongTextContentStripped
 */
export type LongTextContentStripped = {
    lengthLimit: LongTextLength;
    /**
     * Rubric
     */
    rubric?: Array<RubricItem> | null;
};

/**
 * LongTextLength
 */
export enum LongTextLength {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * SHORT
     */
    SHORT = 1,
    /**
     * MEDIUM
     */
    MEDIUM = 2,
    /**
     * LONG
     */
    LONG = 3
}

/**
 * MultipleChoiceContent
 */
export type MultipleChoiceContent = {
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Correctindices
     */
    correctIndices: Array<number>;
};

/**
 * MultipleChoiceContentStripped
 */
export type MultipleChoiceContentStripped = {
    /**
     * Options
     */
    options: Array<string>;
    /**
     * Correctindices
     */
    correctIndices?: Array<number> | null;
};

/**
 * NoteChunkEdit
 */
export type NoteChunkEdit = {
    /**
     * Fulltext
     */
    fullText: string;
    /**
     * Selectedtext
     */
    selectedText: string;
    /**
     * Instructions
     */
    instructions: string;
};

/**
 * NoteChunkEditResponse
 */
export type NoteChunkEditResponse = {
    /**
     * Editedtext
     */
    editedText: string;
};

/**
 * NoteCreate
 */
export type NoteCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Content
     */
    content?: string;
    /**
     * Tags
     */
    tags?: Array<string>;
};

/**
 * NoteGenerate
 */
export type NoteGenerate = {
    /**
     * Topic
     */
    topic: string;
    /**
     * Guidance
     */
    guidance?: string | null;
    length?: NoteLength | null;
};

/**
 * NoteLength
 */
export enum NoteLength {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * SHORT
     */
    SHORT = 1,
    /**
     * MEDIUM
     */
    MEDIUM = 2,
    /**
     * LONG
     */
    LONG = 3
}

/**
 * NoteRead
 */
export type NoteRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Content
     */
    content?: string;
    /**
     * Tags
     */
    tags?: Array<string>;
    /**
     * Id
     */
    id: string;
    /**
     * Userid
     */
    userId: string;
    source: NoteSource;
    /**
     * Createdat
     */
    createdAt: Date;
    /**
     * Updatedat
     */
    updatedAt: Date;
};

/**
 * NoteRefine
 */
export type NoteRefine = {
    /**
     * Instructions
     */
    instructions: string;
};

/**
 * NoteSource
 */
export enum NoteSource {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * USER_CREATED
     */
    USER_CREATED = 1,
    /**
     * AI_GENERATED
     */
    AI_GENERATED = 2
}

/**
 * NoteUpdate
 */
export type NoteUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Content
     */
    content?: string | null;
    /**
     * Tags
     */
    tags?: Array<string> | null;
};

/**
 * PaginatedResponse[QuestionListRead]
 */
export type PaginatedResponseQuestionListRead = {
    /**
     * Items
     */
    items: Array<QuestionListRead>;
    /**
     * Total
     */
    total: number;
    /**
     * Page
     */
    page: number;
    /**
     * Perpage
     */
    perPage: number;
};

/**
 * QuestionAnswer
 *
 * A single answer within a test submission.
 */
export type QuestionAnswer = {
    /**
     * Questionid
     */
    questionId: string;
    /**
     * Useranswer
     */
    userAnswer: string;
};

/**
 * QuestionCheckRequest
 *
 * Payload for checking a single question answer.
 */
export type QuestionCheckRequest = {
    /**
     * Useranswer
     */
    userAnswer: string;
};

/**
 * QuestionCheckResponse
 *
 * Response for a single question check.
 */
export type QuestionCheckResponse = {
    status: AnswerStatus;
    /**
     * Correctanswers
     */
    correctAnswers?: Array<string> | null;
    /**
     * Correctindices
     */
    correctIndices?: Array<number> | null;
    srsState?: SrsStateResponse | null;
};

/**
 * QuestionCreate
 */
export type QuestionCreate = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Testid
     */
    testId?: string | null;
    /**
     * Groupid
     */
    groupId?: string | null;
    /**
     * Order
     */
    order?: number;
    /**
     * Points
     */
    points?: number;
};

/**
 * QuestionCreateStandalone
 *
 * Create a standalone question not attached to any test.
 */
export type QuestionCreateStandalone = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Points
     */
    points?: number;
};

/**
 * QuestionEditRequest
 */
export type QuestionEditRequest = {
    /**
     * Selectedindices
     */
    selectedIndices: Array<number>;
    /**
     * Allquestions
     */
    allQuestions: Array<GeneratedQuestionPreviewInput>;
    /**
     * Instructions
     */
    instructions: string;
    /**
     * Notecontent
     */
    noteContent?: string | null;
};

/**
 * QuestionGroupType
 */
export enum QuestionGroupType {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * VOCABULARY
     */
    VOCABULARY = 1
}

/**
 * QuestionListRead
 *
 * Question with owning test/group names — used in the questions list page.
 */
export type QuestionListRead = {
    /**
     * Id
     */
    id: string;
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Testid
     */
    testId?: string | null;
    /**
     * Groupid
     */
    groupId?: string | null;
    /**
     * Order
     */
    order?: number;
    /**
     * Points
     */
    points?: number;
    /**
     * Originid
     */
    originId?: string | null;
    /**
     * Testtitle
     */
    testTitle?: string | null;
    /**
     * Grouptitle
     */
    groupTitle?: string | null;
};

/**
 * QuestionRead
 */
export type QuestionRead = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Content
     */
    content: SimpleContent | MultipleChoiceContent | LongTextContent;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Testid
     */
    testId?: string | null;
    /**
     * Groupid
     */
    groupId?: string | null;
    /**
     * Order
     */
    order?: number;
    /**
     * Points
     */
    points?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Originid
     */
    originId?: string | null;
};

/**
 * QuestionReadStripped
 *
 * QuestionRead with answer fields optional — used when answers are stripped before serving.
 */
export type QuestionReadStripped = {
    questionType: QuestionType;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Content
     */
    content: LongTextContentStripped | MultipleChoiceContentStripped | SimpleContentStripped;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Testid
     */
    testId?: string | null;
    /**
     * Groupid
     */
    groupId?: string | null;
    /**
     * Order
     */
    order?: number;
    /**
     * Points
     */
    points?: number;
    /**
     * Id
     */
    id: string;
};

/**
 * QuestionType
 */
export enum QuestionType {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * SIMPLE
     */
    SIMPLE = 1,
    /**
     * MULTIPLE_CHOICE
     */
    MULTIPLE_CHOICE = 2,
    /**
     * LONG_TEXT
     */
    LONG_TEXT = 3
}

/**
 * QuestionUpdate
 */
export type QuestionUpdate = {
    questionType?: QuestionType | null;
    /**
     * Prompt
     */
    prompt?: string | null;
    /**
     * Content
     */
    content?: SimpleContent | MultipleChoiceContent | LongTextContent | null;
    /**
     * Hint
     */
    hint?: string | null;
    /**
     * Explanation
     */
    explanation?: string | null;
    /**
     * Points
     */
    points?: number | null;
};

/**
 * ReviewResponse
 */
export type ReviewResponse = {
    /**
     * Questions
     */
    questions: Array<QuestionReadStripped>;
    /**
     * Hasquestions
     */
    hasQuestions: boolean;
};

/**
 * RubricItem
 */
export type RubricItem = {
    /**
     * Point
     *
     * The concept or fact the user must mention
     */
    point: string;
    /**
     * Weight
     *
     * Score contribution (0.0 to 1.0)
     */
    weight: number;
    /**
     * Category
     *
     * Optional grouping label (e.g. 'Key Events')
     */
    category?: string | null;
};

/**
 * RubricResultItem
 */
export type RubricResultItem = {
    /**
     * Point
     */
    point: string;
    /**
     * Met
     */
    met: boolean;
    /**
     * Weight
     */
    weight: number;
    /**
     * Reason
     */
    reason?: string;
    challengeResult?: ChallengeResultItem | null;
};

/**
 * SRSStateResponse
 */
export type SrsStateResponse = {
    /**
     * Easefactor
     */
    easeFactor: number;
    /**
     * Interval
     */
    interval: number;
    /**
     * Repetitions
     */
    repetitions: number;
    /**
     * Nextreview
     */
    nextReview?: Date | null;
};

/**
 * SimpleContent
 */
export type SimpleContent = {
    /**
     * Answers
     */
    answers: Array<string>;
};

/**
 * SimpleContentStripped
 */
export type SimpleContentStripped = {
    /**
     * Answers
     */
    answers?: Array<string> | null;
};

/**
 * TestCreate
 */
export type TestCreate = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Questions
     */
    questions?: Array<QuestionCreate>;
    /**
     * Questiongroups
     */
    questionGroups?: Array<TestQuestionGroupCreate>;
    /**
     * Sourcenoteid
     */
    sourceNoteId?: string | null;
};

/**
 * TestGenerationRequest
 */
export type TestGenerationRequest = {
    /**
     * Noteid
     */
    noteId: string;
    /**
     * Questioncount
     */
    questionCount: number;
    /**
     * Questiontypes
     */
    questionTypes: Array<QuestionType>;
    /**
     * Difficulty
     */
    difficulty: 'easy' | 'medium' | 'hard';
    /**
     * Guidance
     */
    guidance?: string | null;
};

/**
 * TestGenerationResponse
 */
export type TestGenerationResponse = {
    /**
     * Questions
     */
    questions: Array<GeneratedQuestionPreviewOutput>;
    /**
     * Sourcenoteid
     */
    sourceNoteId?: string | null;
    /**
     * Sourcenotetitle
     */
    sourceNoteTitle?: string | null;
    /**
     * Warning
     */
    warning?: string | null;
};

/**
 * TestQuestionGroupCreate
 */
export type TestQuestionGroupCreate = {
    type?: QuestionGroupType;
    /**
     * Order
     */
    order?: number;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Points
     */
    points?: number;
    /**
     * Questions
     */
    questions?: Array<QuestionCreate>;
};

/**
 * TestQuestionGroupRead
 */
export type TestQuestionGroupRead = {
    type?: QuestionGroupType;
    /**
     * Order
     */
    order?: number;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Points
     */
    points?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Testid
     */
    testId: string;
    /**
     * Originid
     */
    originId?: string | null;
    /**
     * Questions
     */
    questions?: Array<QuestionRead>;
};

/**
 * TestQuestionGroupReadStripped
 */
export type TestQuestionGroupReadStripped = {
    type?: QuestionGroupType;
    /**
     * Order
     */
    order?: number;
    /**
     * Title
     */
    title?: string | null;
    /**
     * Points
     */
    points?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Testid
     */
    testId: string;
    /**
     * Questions
     */
    questions?: Array<QuestionReadStripped>;
};

/**
 * TestRead
 */
export type TestRead = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Userid
     */
    userId: string;
    status: TestStatus;
    /**
     * Sourcenoteid
     */
    sourceNoteId?: string | null;
    /**
     * Version
     */
    version?: number;
    /**
     * Parentid
     */
    parentId?: string | null;
    /**
     * Questions
     */
    questions?: Array<QuestionRead>;
    /**
     * Questiongroups
     */
    questionGroups?: Array<TestQuestionGroupRead>;
};

/**
 * TestReadStripped
 */
export type TestReadStripped = {
    /**
     * Title
     */
    title: string;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Id
     */
    id: string;
    /**
     * Userid
     */
    userId: string;
    status: TestStatus;
    /**
     * Questions
     */
    questions?: Array<QuestionReadStripped>;
    /**
     * Questiongroups
     */
    questionGroups?: Array<TestQuestionGroupReadStripped>;
};

/**
 * TestRefinementRequest
 */
export type TestRefinementRequest = {
    /**
     * Noteid
     */
    noteId: string;
    /**
     * Currentquestions
     */
    currentQuestions: Array<GeneratedQuestionPreviewInput>;
    /**
     * Instructions
     */
    instructions: string;
};

/**
 * TestResultListItem
 *
 * Lightweight schema for the history list — no answers array.
 */
export type TestResultListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Testid
     */
    testId: string;
    /**
     * Testtitle
     */
    testTitle: string;
    /**
     * Score
     */
    score?: number;
    /**
     * Totalquestions
     */
    totalQuestions: number;
    /**
     * Correctanswers
     */
    correctAnswers: number;
    /**
     * Pendinganswers
     */
    pendingAnswers?: number;
    /**
     * Earnedpoints
     */
    earnedPoints?: number;
    /**
     * Totalpoints
     */
    totalPoints?: number;
    /**
     * Createdat
     */
    createdAt: Date;
};

/**
 * TestResultRead
 */
export type TestResultRead = {
    /**
     * Testid
     */
    testId: string;
    /**
     * Userid
     */
    userId: string;
    /**
     * Score
     */
    score?: number;
    /**
     * Totalquestions
     */
    totalQuestions: number;
    /**
     * Correctanswers
     */
    correctAnswers: number;
    /**
     * Pendinganswers
     */
    pendingAnswers?: number;
    /**
     * Earnedpoints
     */
    earnedPoints?: number;
    /**
     * Totalpoints
     */
    totalPoints?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Createdat
     */
    createdAt: Date;
    /**
     * Answers
     */
    answers?: Array<AnswerRead>;
};

/**
 * TestStatus
 */
export enum TestStatus {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * ACTIVE
     */
    ACTIVE = 1,
    /**
     * DELETED
     */
    DELETED = 2
}

/**
 * TestSubmission
 *
 * Payload for submitting a full test for correction.
 */
export type TestSubmission = {
    /**
     * Answers
     */
    answers: Array<QuestionAnswer>;
};

/**
 * TestUpdate
 */
export type TestUpdate = {
    /**
     * Title
     */
    title?: string | null;
    /**
     * Description
     */
    description?: string | null;
    /**
     * Questions
     */
    questions?: Array<QuestionCreate> | null;
    /**
     * Questiongroups
     */
    questionGroups?: Array<TestQuestionGroupCreate> | null;
};

/**
 * TokenUsageDailySummary
 */
export type TokenUsageDailySummary = {
    /**
     * Date
     */
    date: Date;
    provider: AiProvider;
    /**
     * Inputtokens
     */
    inputTokens: number;
    /**
     * Outputtokens
     */
    outputTokens: number;
    /**
     * Estimatedcost
     */
    estimatedCost: string | null;
};

/**
 * TokenUsageSummaryResponse
 */
export type TokenUsageSummaryResponse = {
    /**
     * Daily
     */
    daily: Array<TokenUsageDailySummary>;
    /**
     * Totalinputtokens
     */
    totalInputTokens: number;
    /**
     * Totaloutputtokens
     */
    totalOutputTokens: number;
    /**
     * Totalestimatedcost
     */
    totalEstimatedCost: string | null;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Username
     */
    username: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
    status: UserStatus;
    role: UserRole;
    /**
     * Displayname
     */
    displayName?: string | null;
    /**
     * Locale
     */
    locale?: string;
    /**
     * Theme
     */
    theme?: string;
    aiProvider?: AiProvider | null;
    /**
     * Hasanthropickey
     */
    hasAnthropicKey?: boolean;
    /**
     * Hasopenaikey
     */
    hasOpenaiKey?: boolean;
    /**
     * Dailyreviewlimit
     */
    dailyReviewLimit?: number | null;
    /**
     * Initialeasefactor
     */
    initialEaseFactor?: number;
};

/**
 * UserRole
 */
export enum UserRole {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * ADMIN
     */
    ADMIN = 1,
    /**
     * USER
     */
    USER = 2
}

/**
 * UserStatus
 */
export enum UserStatus {
    /**
     * UNKNOWN
     */
    UNKNOWN = 0,
    /**
     * ACTIVE
     */
    ACTIVE = 1,
    /**
     * DELETED
     */
    DELETED = 2,
    /**
     * BLOCKED
     */
    BLOCKED = 3
}

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Displayname
     */
    displayName?: string | null;
    /**
     * Locale
     */
    locale?: string | null;
    /**
     * Theme
     */
    theme?: string | null;
    aiProvider?: AiProvider | null;
    /**
     * Anthropicapikey
     */
    anthropicApiKey?: string | null;
    /**
     * Openaiapikey
     */
    openaiApiKey?: string | null;
    /**
     * Dailyreviewlimit
     */
    dailyReviewLimit?: number | null;
    /**
     * Initialeasefactor
     */
    initialEaseFactor?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type UsersSignupData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersSignupErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersSignupError = UsersSignupErrors[keyof UsersSignupErrors];

export type UsersSignupResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type UsersSignupResponse = UsersSignupResponses[keyof UsersSignupResponses];

export type UsersLoginData = {
    body: BodyUsersLogin;
    path?: never;
    query?: never;
    url: '/api/v1/users/login';
};

export type UsersLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersLoginError = UsersLoginErrors[keyof UsersLoginErrors];

export type UsersLoginResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersLoginResponse = UsersLoginResponses[keyof UsersLoginResponses];

export type UsersRefreshData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/refresh';
};

export type UsersRefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRefreshError = UsersRefreshErrors[keyof UsersRefreshErrors];

export type UsersRefreshResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersRefreshResponse = UsersRefreshResponses[keyof UsersRefreshResponses];

export type UsersLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/logout';
};

export type UsersLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersLogoutResponse = UsersLogoutResponses[keyof UsersLogoutResponses];

export type UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersMeError = UsersMeErrors[keyof UsersMeErrors];

export type UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersMeResponse = UsersMeResponses[keyof UsersMeResponses];

export type UsersUpdateMeData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateMeError = UsersUpdateMeErrors[keyof UsersUpdateMeErrors];

export type UsersUpdateMeResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUpdateMeResponse = UsersUpdateMeResponses[keyof UsersUpdateMeResponses];

export type TestsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/tests';
};

export type TestsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsListError = TestsListErrors[keyof TestsListErrors];

export type TestsListResponses = {
    /**
     * Response Testslist
     *
     * Successful Response
     */
    200: Array<TestRead>;
};

export type TestsListResponse = TestsListResponses[keyof TestsListResponses];

export type TestsCreateData = {
    body: TestCreate;
    path?: never;
    query?: never;
    url: '/api/v1/tests';
};

export type TestsCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsCreateError = TestsCreateErrors[keyof TestsCreateErrors];

export type TestsCreateResponses = {
    /**
     * Successful Response
     */
    201: TestRead;
};

export type TestsCreateResponse = TestsCreateResponses[keyof TestsCreateResponses];

export type TestsDeleteData = {
    body?: never;
    path: {
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_id}';
};

export type TestsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsDeleteError = TestsDeleteErrors[keyof TestsDeleteErrors];

export type TestsDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type TestsDeleteResponse = TestsDeleteResponses[keyof TestsDeleteResponses];

export type TestsGetData = {
    body?: never;
    path: {
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_id}';
};

export type TestsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsGetError = TestsGetErrors[keyof TestsGetErrors];

export type TestsGetResponses = {
    /**
     * Successful Response
     */
    200: TestRead;
};

export type TestsGetResponse = TestsGetResponses[keyof TestsGetResponses];

export type TestsUpdateData = {
    body: TestUpdate;
    path: {
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_id}';
};

export type TestsUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsUpdateError = TestsUpdateErrors[keyof TestsUpdateErrors];

export type TestsUpdateResponses = {
    /**
     * Successful Response
     */
    200: TestRead;
};

export type TestsUpdateResponse = TestsUpdateResponses[keyof TestsUpdateResponses];

export type TestsGetExamData = {
    body?: never;
    path: {
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_id}/exam';
};

export type TestsGetExamErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsGetExamError = TestsGetExamErrors[keyof TestsGetExamErrors];

export type TestsGetExamResponses = {
    /**
     * Successful Response
     */
    200: TestReadStripped;
};

export type TestsGetExamResponse = TestsGetExamResponses[keyof TestsGetExamResponses];

export type TestsGenerateData = {
    body: TestGenerationRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tests/generate';
};

export type TestsGenerateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsGenerateError = TestsGenerateErrors[keyof TestsGenerateErrors];

export type TestsGenerateResponses = {
    /**
     * Successful Response
     */
    200: TestGenerationResponse;
};

export type TestsGenerateResponse = TestsGenerateResponses[keyof TestsGenerateResponses];

export type TestsRefineData = {
    body: TestRefinementRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tests/generate/refine';
};

export type TestsRefineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsRefineError = TestsRefineErrors[keyof TestsRefineErrors];

export type TestsRefineResponses = {
    /**
     * Successful Response
     */
    200: TestGenerationResponse;
};

export type TestsRefineResponse = TestsRefineResponses[keyof TestsRefineResponses];

export type TestsEditQuestionsData = {
    body: QuestionEditRequest;
    path?: never;
    query?: never;
    url: '/api/v1/tests/generate/edit-questions';
};

export type TestsEditQuestionsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsEditQuestionsError = TestsEditQuestionsErrors[keyof TestsEditQuestionsErrors];

export type TestsEditQuestionsResponses = {
    /**
     * Successful Response
     */
    200: TestGenerationResponse;
};

export type TestsEditQuestionsResponse = TestsEditQuestionsResponses[keyof TestsEditQuestionsResponses];

export type TestsSubmitData = {
    body: TestSubmission;
    path: {
        /**
         * Test Id
         */
        test_id: string;
    };
    query?: never;
    url: '/api/v1/tests/{test_id}/submit';
};

export type TestsSubmitErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TestsSubmitError = TestsSubmitErrors[keyof TestsSubmitErrors];

export type TestsSubmitResponses = {
    /**
     * Successful Response
     */
    201: TestResultRead;
};

export type TestsSubmitResponse = TestsSubmitResponses[keyof TestsSubmitResponses];

export type ResultsListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/results';
};

export type ResultsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResultsListError = ResultsListErrors[keyof ResultsListErrors];

export type ResultsListResponses = {
    /**
     * Response Resultslist
     *
     * Successful Response
     */
    200: Array<TestResultListItem>;
};

export type ResultsListResponse = ResultsListResponses[keyof ResultsListResponses];

export type ResultsGetData = {
    body?: never;
    path: {
        /**
         * Result Id
         */
        result_id: string;
    };
    query?: never;
    url: '/api/v1/results/{result_id}';
};

export type ResultsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResultsGetError = ResultsGetErrors[keyof ResultsGetErrors];

export type ResultsGetResponses = {
    /**
     * Successful Response
     */
    200: TestResultRead;
};

export type ResultsGetResponse = ResultsGetResponses[keyof ResultsGetResponses];

export type QuestionsListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Question Type
         */
        question_type?: Array<number> | null;
        /**
         * Test Id
         */
        test_id?: Array<string> | null;
        /**
         * Search
         */
        search?: string | null;
        /**
         * Grouping
         */
        grouping?: 'grouped' | 'ungrouped' | null;
        /**
         * Sort By
         */
        sort_by?: 'prompt' | 'question_type' | 'points' | 'created_at' | null;
        /**
         * Sort Order
         */
        sort_order?: 'asc' | 'desc';
        /**
         * Page
         */
        page?: number;
        /**
         * Per Page
         */
        per_page?: number;
    };
    url: '/api/v1/questions';
};

export type QuestionsListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsListError = QuestionsListErrors[keyof QuestionsListErrors];

export type QuestionsListResponses = {
    /**
     * Successful Response
     */
    200: PaginatedResponseQuestionListRead;
};

export type QuestionsListResponse = QuestionsListResponses[keyof QuestionsListResponses];

export type QuestionsCreateData = {
    body: QuestionCreateStandalone;
    path?: never;
    query?: never;
    url: '/api/v1/questions';
};

export type QuestionsCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsCreateError = QuestionsCreateErrors[keyof QuestionsCreateErrors];

export type QuestionsCreateResponses = {
    /**
     * Successful Response
     */
    201: QuestionRead;
};

export type QuestionsCreateResponse = QuestionsCreateResponses[keyof QuestionsCreateResponses];

export type QuestionsDeleteData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type QuestionsDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsDeleteError = QuestionsDeleteErrors[keyof QuestionsDeleteErrors];

export type QuestionsDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type QuestionsDeleteResponse = QuestionsDeleteResponses[keyof QuestionsDeleteResponses];

export type QuestionsGetData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type QuestionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsGetError = QuestionsGetErrors[keyof QuestionsGetErrors];

export type QuestionsGetResponses = {
    /**
     * Successful Response
     */
    200: QuestionRead;
};

export type QuestionsGetResponse = QuestionsGetResponses[keyof QuestionsGetResponses];

export type QuestionsUpdateData = {
    body: QuestionUpdate;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}';
};

export type QuestionsUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsUpdateError = QuestionsUpdateErrors[keyof QuestionsUpdateErrors];

export type QuestionsUpdateResponses = {
    /**
     * Successful Response
     */
    200: QuestionRead;
};

export type QuestionsUpdateResponse = QuestionsUpdateResponses[keyof QuestionsUpdateResponses];

export type QuestionsCheckData = {
    body: QuestionCheckRequest;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}/check';
};

export type QuestionsCheckErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsCheckError = QuestionsCheckErrors[keyof QuestionsCheckErrors];

export type QuestionsCheckResponses = {
    /**
     * Successful Response
     */
    200: QuestionCheckResponse;
};

export type QuestionsCheckResponse = QuestionsCheckResponses[keyof QuestionsCheckResponses];

export type QuestionsAssignToTestData = {
    body: AssignQuestionRequest;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}/assign';
};

export type QuestionsAssignToTestErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsAssignToTestError = QuestionsAssignToTestErrors[keyof QuestionsAssignToTestErrors];

export type QuestionsAssignToTestResponses = {
    /**
     * Successful Response
     */
    201: QuestionRead;
};

export type QuestionsAssignToTestResponse = QuestionsAssignToTestResponses[keyof QuestionsAssignToTestResponses];

export type QuestionsDuplicateData = {
    body?: never;
    path: {
        /**
         * Question Id
         */
        question_id: string;
    };
    query?: never;
    url: '/api/v1/questions/{question_id}/duplicate';
};

export type QuestionsDuplicateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsDuplicateError = QuestionsDuplicateErrors[keyof QuestionsDuplicateErrors];

export type QuestionsDuplicateResponses = {
    /**
     * Successful Response
     */
    201: QuestionRead;
};

export type QuestionsDuplicateResponse = QuestionsDuplicateResponses[keyof QuestionsDuplicateResponses];

export type QuestionsBulkDeleteData = {
    body: BulkDeleteQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/questions/bulk-delete';
};

export type QuestionsBulkDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsBulkDeleteError = QuestionsBulkDeleteErrors[keyof QuestionsBulkDeleteErrors];

export type QuestionsBulkDeleteResponses = {
    /**
     * Successful Response
     */
    200: BulkDeleteQuestionsResponse;
};

export type QuestionsBulkDeleteResponse = QuestionsBulkDeleteResponses[keyof QuestionsBulkDeleteResponses];

export type QuestionsBulkAssignData = {
    body: BulkAssignQuestionsRequest;
    path?: never;
    query?: never;
    url: '/api/v1/questions/bulk-assign';
};

export type QuestionsBulkAssignErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type QuestionsBulkAssignError = QuestionsBulkAssignErrors[keyof QuestionsBulkAssignErrors];

export type QuestionsBulkAssignResponses = {
    /**
     * Successful Response
     */
    200: BulkAssignQuestionsResponse;
};

export type QuestionsBulkAssignResponse = QuestionsBulkAssignResponses[keyof QuestionsBulkAssignResponses];

export type AnswersChallengeData = {
    body: ChallengeRequest;
    path: {
        /**
         * Answer Id
         */
        answer_id: string;
    };
    query?: never;
    url: '/api/v1/answers/{answer_id}/challenge';
};

export type AnswersChallengeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AnswersChallengeError = AnswersChallengeErrors[keyof AnswersChallengeErrors];

export type AnswersChallengeResponses = {
    /**
     * Successful Response
     */
    200: AnswerRead;
};

export type AnswersChallengeResponse = AnswersChallengeResponses[keyof AnswersChallengeResponses];

export type ReviewListData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Mode
         */
        mode?: string;
    };
    url: '/api/v1/review/questions';
};

export type ReviewListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReviewListError = ReviewListErrors[keyof ReviewListErrors];

export type ReviewListResponses = {
    /**
     * Successful Response
     */
    200: ReviewResponse;
};

export type ReviewListResponse = ReviewListResponses[keyof ReviewListResponses];

export type NotesListData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/notes';
};

export type NotesListErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesListError = NotesListErrors[keyof NotesListErrors];

export type NotesListResponses = {
    /**
     * Response Noteslist
     *
     * Successful Response
     */
    200: Array<NoteRead>;
};

export type NotesListResponse = NotesListResponses[keyof NotesListResponses];

export type NotesCreateData = {
    body: NoteCreate;
    path?: never;
    query?: never;
    url: '/api/v1/notes';
};

export type NotesCreateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesCreateError = NotesCreateErrors[keyof NotesCreateErrors];

export type NotesCreateResponses = {
    /**
     * Successful Response
     */
    201: NoteRead;
};

export type NotesCreateResponse = NotesCreateResponses[keyof NotesCreateResponses];

export type NotesGenerateData = {
    body: NoteGenerate;
    path?: never;
    query?: never;
    url: '/api/v1/notes/generate';
};

export type NotesGenerateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesGenerateError = NotesGenerateErrors[keyof NotesGenerateErrors];

export type NotesGenerateResponses = {
    /**
     * Successful Response
     */
    201: NoteRead;
};

export type NotesGenerateResponse = NotesGenerateResponses[keyof NotesGenerateResponses];

export type NotesDeleteData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type NotesDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesDeleteError = NotesDeleteErrors[keyof NotesDeleteErrors];

export type NotesDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type NotesDeleteResponse = NotesDeleteResponses[keyof NotesDeleteResponses];

export type NotesGetData = {
    body?: never;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type NotesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesGetError = NotesGetErrors[keyof NotesGetErrors];

export type NotesGetResponses = {
    /**
     * Successful Response
     */
    200: NoteRead;
};

export type NotesGetResponse = NotesGetResponses[keyof NotesGetResponses];

export type NotesUpdateData = {
    body: NoteUpdate;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}';
};

export type NotesUpdateErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesUpdateError = NotesUpdateErrors[keyof NotesUpdateErrors];

export type NotesUpdateResponses = {
    /**
     * Successful Response
     */
    200: NoteRead;
};

export type NotesUpdateResponse = NotesUpdateResponses[keyof NotesUpdateResponses];

export type NotesRefineData = {
    body: NoteRefine;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/refine';
};

export type NotesRefineErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesRefineError = NotesRefineErrors[keyof NotesRefineErrors];

export type NotesRefineResponses = {
    /**
     * Successful Response
     */
    200: NoteRead;
};

export type NotesRefineResponse = NotesRefineResponses[keyof NotesRefineResponses];

export type NotesEditChunkData = {
    body: NoteChunkEdit;
    path: {
        /**
         * Note Id
         */
        note_id: string;
    };
    query?: never;
    url: '/api/v1/notes/{note_id}/edit-chunk';
};

export type NotesEditChunkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type NotesEditChunkError = NotesEditChunkErrors[keyof NotesEditChunkErrors];

export type NotesEditChunkResponses = {
    /**
     * Successful Response
     */
    200: NoteChunkEditResponse;
};

export type NotesEditChunkResponse = NotesEditChunkResponses[keyof NotesEditChunkResponses];

export type TokenUsageGetUsageData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Days
         */
        days?: number;
    };
    url: '/api/v1/token-usage';
};

export type TokenUsageGetUsageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type TokenUsageGetUsageError = TokenUsageGetUsageErrors[keyof TokenUsageGetUsageErrors];

export type TokenUsageGetUsageResponses = {
    /**
     * Successful Response
     */
    200: TokenUsageSummaryResponse;
};

export type TokenUsageGetUsageResponse = TokenUsageGetUsageResponses[keyof TokenUsageGetUsageResponses];

export type DefaultHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type DefaultHealthResponses = {
    /**
     * Response Defaulthealth
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type DefaultHealthResponse = DefaultHealthResponses[keyof DefaultHealthResponses];
