"""add_source_note_id_to_test

Revision ID: 0ab16b13962c
Revises: 1de08945ea18
Create Date: 2026-07-14 16:12:32.013714

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ab16b13962c"
down_revision: str | Sequence[str] | None = "1de08945ea18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("test", sa.Column("source_note_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(None, "test", "note", ["source_note_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "test", type_="foreignkey")
    op.drop_column("test", "source_note_id")
    # ### end Alembic commands ###
