"""add description and tags to note

Revision ID: 1de08945ea18
Revises: 011d8b442d08
Create Date: 2026-07-10 15:43:27.359984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1de08945ea18'
down_revision: Union[str, Sequence[str], None] = '011d8b442d08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('description', sa.String(length=500), nullable=True))
    op.add_column('note', sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'tags')
    op.drop_column('note', 'description')
    # ### end Alembic commands ###
