"""add user ai tool permissions

Revision ID: 3b3a78595fc9
Revises: 211b039e2059
Create Date: 2026-10-04 11:45:02.092818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3b3a78595fc9'
down_revision: Union[str, Sequence[str], None] = '211b039e2059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('ai_tool_permissions', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'ai_tool_permissions')
    # ### end Alembic commands ###
