"""replace_unique_constraints_with_partial_indexes

Revision ID: 4f15c5394e25
Revises: c7f8a9b0d1e2
Create Date: 2026-08-20 17:24:42.671029

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f15c5394e25"
down_revision: str | Sequence[str] | None = "c7f8a9b0d1e2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_group_question_order"), "question", type_="unique")
    op.create_index(
        "uq_group_question_order",
        "question",
        ["group_id", "order"],
        unique=True,
        postgresql_where=sa.text("status = 1"),
    )
    op.drop_constraint(op.f("uq_test_question_order"), "question", type_="unique")
    op.create_index(
        "uq_test_question_order", "question", ["test_id", "order"], unique=True, postgresql_where=sa.text("status = 1")
    )
    op.drop_constraint(op.f("uq_test_group_order"), "test_question_group", type_="unique")
    op.create_index(
        "uq_test_group_order",
        "test_question_group",
        ["test_id", "order"],
        unique=True,
        postgresql_where=sa.text("status = 1"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("uq_test_group_order", table_name="test_question_group", postgresql_where=sa.text("status = 1"))
    op.create_unique_constraint(
        op.f("uq_test_group_order"), "test_question_group", ["test_id", "order"], postgresql_nulls_not_distinct=False
    )
    op.drop_index("uq_test_question_order", table_name="question", postgresql_where=sa.text("status = 1"))
    op.create_unique_constraint(
        op.f("uq_test_question_order"), "question", ["test_id", "order"], postgresql_nulls_not_distinct=False
    )
    op.drop_index("uq_group_question_order", table_name="question", postgresql_where=sa.text("status = 1"))
    op.create_unique_constraint(
        op.f("uq_group_question_order"), "question", ["group_id", "order"], postgresql_nulls_not_distinct=False
    )
    # ### end Alembic commands ###
