"""add index on test parent_id

Revision ID: 74880ffd2725
Revises: acbc3802ce15
Create Date: 2026-07-28 21:49:26.792397

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "74880ffd2725"
down_revision: str | Sequence[str] | None = "acbc3802ce15"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_test_parent_id"), "test", ["parent_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_test_parent_id"), table_name="test")
    # ### end Alembic commands ###
