"""add model_pricing table and estimated_cost to token_usage

Revision ID: acafabfbdcba
Revises: d343a2d509b0
Create Date: 2026-07-26 10:22:41.774499

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acafabfbdcba"
down_revision: str | Sequence[str] | None = "d343a2d509b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "model_pricing",
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column("model_id", sa.String(length=100), nullable=False),
        sa.Column("input_price", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("output_price", sa.Numeric(precision=18, scale=12), nullable=False),
        sa.Column("valid_from", sa.Date(), nullable=False),
        sa.Column("valid_to", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_model_pricing_model_valid", "model_pricing", ["model_id", "valid_from"], unique=False)
    op.add_column("token_usage", sa.Column("estimated_cost", sa.Numeric(precision=12, scale=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("token_usage", "estimated_cost")
    op.drop_index("ix_model_pricing_model_valid", table_name="model_pricing")
    op.drop_table("model_pricing")
    # ### end Alembic commands ###
