"""add test versioning columns

Revision ID: acbc3802ce15
Revises: be444d8d707a
Create Date: 2026-07-27 16:03:46.684412

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "acbc3802ce15"
down_revision: str | Sequence[str] | None = "be444d8d707a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("origin_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(None, "question", "question", ["origin_id"], ["id"], ondelete="SET NULL")
    op.add_column("test", sa.Column("version", sa.Integer(), server_default="1", nullable=False))
    op.add_column("test", sa.Column("parent_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(None, "test", "test", ["parent_id"], ["id"], ondelete="SET NULL")
    op.add_column("test_question_group", sa.Column("origin_id", sa.String(length=26), nullable=True))
    op.create_foreign_key(
        None, "test_question_group", "test_question_group", ["origin_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "test_question_group", type_="foreignkey")
    op.drop_column("test_question_group", "origin_id")
    op.drop_constraint(None, "test", type_="foreignkey")
    op.drop_column("test", "parent_id")
    op.drop_column("test", "version")
    op.drop_constraint(None, "question", type_="foreignkey")
    op.drop_column("question", "origin_id")
    # ### end Alembic commands ###
