"""question_group_title

Revision ID: b2b2104d074f
Revises: fcd2180eabed
Create Date: 2026-04-04 12:55:14.256428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2b2104d074f'
down_revision: Union[str, Sequence[str], None] = 'fcd2180eabed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_question_group', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_question_group', 'title')
    # ### end Alembic commands ###
