"""add_points_and_scoring_columns

Revision ID: b4b395386cf7
Revises: f976d2c6f94a
Create Date: 2026-06-06 22:36:45.121177

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b4b395386cf7"
down_revision: str | Sequence[str] | None = "f976d2c6f94a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("points", sa.Float(), server_default="1.0", nullable=False))
    op.add_column("test_question_group", sa.Column("points", sa.Float(), server_default="1.0", nullable=False))
    op.add_column("test_result", sa.Column("earned_points", sa.Float(), server_default="0", nullable=False))
    op.add_column("test_result", sa.Column("total_points", sa.Float(), server_default="0", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_result", "total_points")
    op.drop_column("test_result", "earned_points")
    op.drop_column("test_question_group", "points")
    op.drop_column("question", "points")
    # ### end Alembic commands ###
