"""add status to question and test_question_group

Revision ID: be444d8d707a
Revises: acafabfbdcba
Create Date: 2026-07-26 14:47:27.858348

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be444d8d707a"
down_revision: str | Sequence[str] | None = "acafabfbdcba"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("question", sa.Column("status", sa.Integer(), server_default="1", nullable=False))
    op.add_column("test_question_group", sa.Column("status", sa.Integer(), server_default="1", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("test_question_group", "status")
    op.drop_column("question", "status")
    # ### end Alembic commands ###
